language: python
python:
  - 3.5
env:
  global:
    - PYTHONPATH=$PYTHONPATH:$TRAVIS_BUILD_DIR/common
addons:
  apt:
    sources:
      - sourceline: 'deb http://repo.mysql.com/apt/ubuntu/ trusty mysql-5.7'
        key_url: https://gist.githubusercontent.com/desertkun/75e336c160f408e450e5f01a1ded0123/raw/4320b968b1fcee97d5eac85b30722fbeecd5135c/mysql_pubkey.asc
    packages:
      - mysql-server
dist: trusty
sudo: required
before_install:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS test;'
services:
  - mysql
  - redis-server
  - rabbitmq
cache:
  directories:
   - $TRAVIS_BUILD_DIR/v8py
install:
  - git clone https://github.com/anthill-platform/anthill-common $TRAVIS_BUILD_DIR/common
  - python $TRAVIS_BUILD_DIR/common/setup.py install
  - python setup.py install
script:
  - python -m anthill.common.testing --js_source_path="$TRAVIS_BUILD_DIR/js_build"
